### ISSUE TITLE
Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by masyanru** [Tsynapse/Postto-Mattermost#1]
I found intresting issue on Windows Server 2012 R2.
I got "Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel."
At C:\ps\mattermost.ps1:21 char:1
- Invoke-WebRequest `
- ~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
  - FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

and after that you can see an event "A fatal alert was received from the remote endpoint. The TLS protocol defined fatal alert code is 40." Code 40 is handshake_failure. Indicates that the sender was unable to negotiate an acceptable set of security parameters given the options available. This is a fatal error.

but If you run on Windows 10 with
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
Invoke-WebRequest will work perfectly.

**Comment by Tsynapse** [comment]
Hmm let me take a look.  Is the Server 2012R2 box up to date with the latest patches?

**Comment by masyanru** [comment]
yep
![image](https://cloud.githubusercontent.com/assets/19715692/18717450/9b7797ce-8028-11e6-85f5-a34ce2e9cddb.png)

**Comment by Tsynapse** [comment]
I'm seeing this with several other applications as well, and I'm not sure that changing the TLS settings in this function is the best thing to do.  I will add a comment to the readme with your workaround.
